CREATE TABLE [dbo].[ApplicationUser] (
    [UserId]             INT            IDENTITY (1, 1) NOT NULL,
    [UserTypeId]         INT            NOT NULL,
    [EmployeeId]         BIGINT         NULL,
    [Username]           VARCHAR (100)  NOT NULL,
    [PasswordHash]       NVARCHAR (500) NOT NULL,
    [PasswordSalt]       NVARCHAR (500) NOT NULL,
    [EmailAddress]       NVARCHAR (150) NULL,
    [MobileNumber]       VARCHAR (20)   NULL,
    [IsEmailVerified]    BIT            DEFAULT ((0)) NOT NULL,
    [IsMobileVerified]   BIT            DEFAULT ((0)) NOT NULL,
    [FailedLoginCount]   INT            DEFAULT ((0)) NOT NULL,
    [IsLocked]           BIT            DEFAULT ((0)) NOT NULL,
    [LockUntil]          DATETIME2 (7)  NULL,
    [LastLoginOn]        DATETIME2 (7)  NULL,
    [PasswordChangedOn]  DATETIME2 (7)  NULL,
    [MustChangePassword] BIT            DEFAULT ((1)) NOT NULL,
    [IsActive]           BIT            DEFAULT ((1)) NOT NULL,
    [CreatedBy]          INT            NULL,
    [CreatedOn]          DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [ModifiedBy]         INT            NULL,
    [ModifiedOn]         DATETIME2 (7)  NULL,
    [RowVersion]         ROWVERSION     NOT NULL,
    [FullName]           VARCHAR (50)   NULL,
    [Email]              VARCHAR (50)   NULL,
    [Mobile]             VARCHAR (50)   NULL,
    PRIMARY KEY CLUSTERED ([UserId] ASC),
    CONSTRAINT [FK_ApplicationUser_UserType] FOREIGN KEY ([UserTypeId]) REFERENCES [dbo].[UserType] ([UserTypeId]),
    UNIQUE NONCLUSTERED ([Username] ASC)
);

