CREATE TABLE [dbo].[Employee] (
    [EmployeeId]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [EmployeeNumber]       VARCHAR (30)   NOT NULL,
    [FirstName]            NVARCHAR (100) NOT NULL,
    [MiddleName]           NVARCHAR (100) NULL,
    [LastName]             NVARCHAR (100) NULL,
    [GenderId]             INT            NULL,
    [DateOfBirth]          DATE           NULL,
    [EmploymentTypeId]     INT            NULL,
    [DesignationId]        INT            NULL,
    [JoiningDate]          DATE           NOT NULL,
    [RelievingDate]        DATE           NULL,
    [EmailAddress]         NVARCHAR (150) NULL,
    [MobileNumber]         VARCHAR (20)   NULL,
    [EmergencyContactName] NVARCHAR (100) NULL,
    [EmergencyContactNo]   VARCHAR (20)   NULL,
    [AadhaarNumber]        VARCHAR (20)   NULL,
    [PANNumber]            VARCHAR (20)   NULL,
    [BloodGroup]           VARCHAR (10)   NULL,
    [IsActive]             BIT            DEFAULT ((1)) NULL,
    [CreatedBy]            INT            NULL,
    [CreatedOn]            DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [ModifiedBy]           INT            NULL,
    [ModifiedOn]           DATETIME2 (7)  NULL,
    [RowVersion]           ROWVERSION     NOT NULL,
    PRIMARY KEY CLUSTERED ([EmployeeId] ASC),
    CONSTRAINT [FK_Employee_Designation] FOREIGN KEY ([DesignationId]) REFERENCES [dbo].[Designation] ([DesignationId]),
    CONSTRAINT [FK_Employee_EmploymentType] FOREIGN KEY ([EmploymentTypeId]) REFERENCES [dbo].[EmploymentType] ([EmploymentTypeId]),
    CONSTRAINT [FK_Employee_Gender] FOREIGN KEY ([GenderId]) REFERENCES [dbo].[Gender] ([GenderId]),
    UNIQUE NONCLUSTERED ([EmployeeNumber] ASC)
);

